project:
  type: website

website:
  title: "Caleb Kirsch"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: " "
##      - about.qmd
    right:
      - icon: github
        href: https://github.com/pomegranatebee/quartoportfolio
      - icon: linkedin
        href: https://www.linkedin.com/in/calebkirsch        
  page-footer:
    left: |
      *This website is built with [![](assets/quarto.png){width=80px}](https://quarto.org/) and hosted via [GitHub](https://github.com/pomegranatebee/quartoportfolio) and [Netlify](https://www.netlify.com/)*
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

