project:
  type: website

website:
  title: "Caleb Kirsch"
  favicon: "assets/Power BI logo.png"
  google-analytics: "G-GR6BB3VRLC"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: " "
      - Portfolio.qmd
      - Personal.qmd
    right:
      - icon: github
        href: https://github.com/pomegranatebee/
      - icon: linkedin
        href: https://www.linkedin.com/in/calebkirsch        
  page-footer:
    left: |
      *This website is built with [![](assets/quarto.png){width=80px}](https://quarto.org/) and hosted via [GitHub](https://github.com/pomegranatebee/quartoportfolio) and [Netlify](https://www.netlify.com/)*
format:
  html:
    theme:
      dark: darkly
      light: flatly
    fontsize: medium
    css: styles.css

editor: visual

