project:
  type: website

website:
  title: "Caleb Kirsch"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: " "
##      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css

editor: visual

